# Generated by Django 5.2.16 on 2026-07-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='monthly_listeners',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='total_streams',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
