# Generated by Django 5.2.16 on 2026-07-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='album-covers/')),
                ('cover_seed', models.CharField(blank=True, max_length=120)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('pop', 'پاپ'), ('rock', 'راک'), ('traditional', 'سنتی'), ('electronic', 'الکترونیک'), ('hiphop', 'هیپ\u200cهاپ'), ('classical', 'کلاسیک'), ('jazz', 'جز'), ('folk', 'فولک')], max_length=16)),
                ('type', models.CharField(choices=[('album', 'آلبوم'), ('single', 'تک\u200cآهنگ')], default='album', max_length=8)),
                ('early_access', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_credits', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_credits', to='accounts.artist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='catalog.AlbumArtist', to='accounts.artist'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('track_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='song-covers/')),
                ('cover_seed', models.CharField(blank=True, max_length=120)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(choices=[('pop', 'پاپ'), ('rock', 'راک'), ('traditional', 'سنتی'), ('electronic', 'الکترونیک'), ('hiphop', 'هیپ\u200cهاپ'), ('classical', 'کلاسیک'), ('jazz', 'جز'), ('folk', 'فولک')], max_length=16)),
                ('release_date', models.DateField()),
                ('lyrics', models.TextField(blank=True)),
                ('early_access', models.BooleanField(default=False)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('listener_count', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='catalog.album')),
            ],
            options={
                'ordering': ['track_number', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_credits', to='accounts.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_credits', to='catalog.song')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', through='catalog.SongArtist', to='accounts.artist'),
        ),
        migrations.AddConstraint(
            model_name='albumartist',
            constraint=models.UniqueConstraint(fields=('album', 'artist'), name='unique_album_artist'),
        ),
        migrations.AddConstraint(
            model_name='songartist',
            constraint=models.UniqueConstraint(fields=('song', 'artist'), name='unique_song_artist'),
        ),
    ]
