# Generated by Django 5.2.16 on 2026-07-23 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='year-month key, e.g. 1405-03', max_length=16)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('reward_toman', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('settled', 'تسویه\u200cشده')], default='pending', max_length=16)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.artist')),
            ],
            options={
                'ordering': ['artist__name'],
                'constraints': [models.UniqueConstraint(fields=('artist', 'period'), name='unique_artist_period')],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='catalog.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='reports_str_user_id_6de6d2_idx'), models.Index(fields=['song', 'created_at'], name='reports_str_song_id_570144_idx')],
            },
        ),
    ]
