# Generated by Django 5.2.16 on 2026-07-23 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_price', models.PositiveIntegerField(default=79000)),
                ('gold_price', models.PositiveIntegerField(default=149000)),
            ],
            options={
                'verbose_name': 'platform settings',
                'verbose_name_plural': 'platform settings',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('basic', 'پایه'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی')], max_length=16)),
                ('billing_period', models.PositiveSmallIntegerField(help_text='months')),
                ('price_paid', models.PositiveIntegerField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('basic', 'پایه'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی')], max_length=16)),
                ('billing_period', models.PositiveSmallIntegerField(help_text='months')),
                ('amount', models.PositiveIntegerField()),
                ('gateway', models.CharField(max_length=32)),
                ('authority', models.CharField(blank=True, max_length=128)),
                ('ref_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
