# Generated by Django 5.2.16 on 2026-08-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payout_per_listener',
            field=models.PositiveIntegerField(default=50, help_text='Toman paid per unique listener in the period'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payout_per_stream',
            field=models.PositiveIntegerField(default=2, help_text='Toman paid per recorded stream'),
        ),
    ]
